apiVersion: v1
kind: ReplicationController
metadata:
  name: my-rc1
spec:
  replicas: 1
  selector:
    env: dev
  template:
    metadata:
      labels:
        env: dev
    spec: 
      containers:
      - name: my-pod
        image: ahmedgawishdocker/palindrome_qlik 
        ports:
        - containerPort: 4444
